CC = gcc
CFLAGS = -Wall -Wextra -std=c99

all: task1 task2 task3 task4

task1: task1.c
	$(CC) $(CFLAGS) -o task1 task1.c

task2: task2.c
	$(CC) $(CFLAGS) -o task2 task2.c

task3: task3.c
	$(CC) $(CFLAGS) -o task3 task3.c

task4: task4.c
	$(CC) $(CFLAGS) -o task4 task4.c

clean:
	rm -f task1 task2 task3 task4